// playgrounds/vite-react/src/main.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { createConfig } from '@growae/reactive'
import { testnet } from '@growae/reactive'
import { ReactiveProvider } from '@growae/reactive-react'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { App } from './App.js'

const config = createConfig({
  networks: [testnet],
  connectors: [],
})

const queryClient = new QueryClient()

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <ReactiveProvider config={config}>
        <App />
      </ReactiveProvider>
    </QueryClientProvider>
  </StrictMode>,
)

// packages/create-reactive/templates/vite-solid/src/index.tsx
import { createConfig } from '@growae/reactive'
import { ReactiveProvider } from '@growae/reactive-solid'
import { testnet } from '@growae/reactive/networks'
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query'
import { render } from 'solid-js/web'

import App from './App.tsx'

const config = createConfig({
  networks: [testnet],
  connectors: [],
})

const queryClient = new QueryClient()

render(
  () => (
    <ReactiveProvider config={config}>
      <QueryClientProvider client={queryClient}>
        <App />
      </QueryClientProvider>
    </ReactiveProvider>
  ),
  document.getElementById('root')!,
)
