// playgrounds/vite-solid/src/App.tsx
import { useNetworkId, useHeight } from '@growae/reactive-solid'

export function App() {
  const networkId = useNetworkId()
  const height = useHeight()

  return (
    <div style={{ 'font-family': 'system-ui', padding: '2rem' }}>
      <h1>Reactive + Solid</h1>
      <p>Network: {networkId.data ?? 'loading...'}</p>
      <p>Height: {height.data?.toString() ?? 'loading...'}</p>
    </div>
  )
}

// playgrounds/vite-vue/src/App.vue
<template>
  <div style="font-family: system-ui; padding: 2rem">
    <h1>Reactive + Vue</h1>
    <p>Network: {{ networkId ?? 'loading...' }}</p>
    <p>Height: {{ height?.toString() ?? 'loading...' }}</p>
  </div>
</template>

<script setup lang="ts">
import { useNetworkId, useHeight } from '@growae/reactive-vue'

const { data: networkId } = useNetworkId()
const { data: height } = useHeight()
</script>
