// packages/react/src/hydrate.ts
'use client'

import { hydrate } from '@reactive/core'
import type { Config, State } from '@reactive/core'
import { type ReactElement, useEffect, useRef } from 'react'

export type HydrateProps = {
  config: Config
  initialState?: State | undefined
  reconnectOnMount?: boolean | undefined
}

export function Hydrate(parameters: React.PropsWithChildren<HydrateProps>) {
  const { children, config, initialState, reconnectOnMount = true } = parameters

  const { onMount } = hydrate(config, {
    initialState,
    reconnectOnMount,
  })

  if (!config._internal.ssr) onMount()

  const active = useRef(true)
  useEffect(() => {
    if (!active.current) return
    if (!config._internal.ssr) return
    onMount()
    return () => {
      active.current = false
    }
  }, [])

  return children as ReactElement
}

// packages/solid/src/hydrate.ts
import { hydrate } from '@reactive/core'
import type { Config, State } from '@reactive/core'
import { mergeProps, onMount, type ParentProps } from 'solid-js'

export type HydrateProps = {
  config: Config
  initialState?: State | undefined
  reconnectOnMount?: boolean | undefined
}

export function Hydrate(parameters: ParentProps<HydrateProps>) {
  const props = mergeProps({ reconnectOnMount: true }, parameters)

  const { onMount: hydrateOnMount } = hydrate(props.config, {
    initialState: props.initialState,
    reconnectOnMount: props.reconnectOnMount,
  })

  if (!props.config._internal.ssr) hydrateOnMount()

  onMount(() => {
    if (!props.config._internal.ssr) return
    hydrateOnMount()
  })

  return props.children
}
