// packages/create-reactive/templates/vite-vue/src/App.vue
<script setup lang="ts">
import { useConnect, useDisconnect, useBalance } from '@growae/reactive-vue'

const { connect, connectors, status, error } = useConnect()
const { disconnect } = useDisconnect()
const { data: balance } = useBalance()
</script>

<template>
  <div>
    <h1>Reactive App</h1>

    <div>
      <h2>Connect</h2>
      <button
        v-for="connector in connectors"
        :key="connector.uid"
        @click="connect({ connector })"
      >
        {{ connector.name }}
      </button>
      <div>{{ status }}</div>
      <div v-if="error">{{ error.message }}</div>
    </div>

    <div v-if="balance !== undefined">
      <h2>Balance</h2>
      <p>{{ balance }} aettos</p>
    </div>

    <button @click="disconnect()">Disconnect</button>
  </div>
</template>

// packages/create-reactive/templates/vite-react/src/App.tsx
import { useBalance, useConnect, useDisconnect } from '@growae/reactive-react'

function App() {
  const { connect, connectors, status, error } = useConnect()
  const { disconnect } = useDisconnect()
  const { data: balance } = useBalance()

  return (
    <div>
      <h1>Reactive App</h1>

      <div>
        <h2>Connect</h2>
        {connectors.map((connector) => (
          <button
            key={connector.uid}
            onClick={() => connect({ connector })}
            type="button"
          >
            {connector.name}
          </button>
        ))}
        <div>{status}</div>
        {error && <div>{error.message}</div>}
      </div>

      {balance !== undefined && (
        <div>
          <h2>Balance</h2>
          <p>{balance.toString()} aettos</p>
        </div>
      )}

      <button type="button" onClick={() => disconnect()}>
        Disconnect
      </button>
    </div>
  )
}

export default App
