// packages/create-reactive/templates/vite-solid/src/index.tsx
import { createConfig } from '@growae/reactive'
import { ReactiveProvider } from '@growae/reactive-solid'
import { testnet } from '@growae/reactive/networks'
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query'
import { render } from 'solid-js/web'

import App from './App.tsx'

const config = createConfig({
  networks: [testnet],
  connectors: [],
})

const queryClient = new QueryClient()

render(
  () => (
    <ReactiveProvider config={config}>
      <QueryClientProvider client={queryClient}>
        <App />
      </QueryClientProvider>
    </ReactiveProvider>
  ),
  document.getElementById('root')!,
)

// packages/create-reactive/templates/vite-react/src/main.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import React from 'react'
import ReactDOM from 'react-dom/client'
import { ReactiveProvider } from '@growae/reactive-react'

import App from './App.tsx'
import { config } from './reactive.ts'

const queryClient = new QueryClient()

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <ReactiveProvider config={config}>
      <QueryClientProvider client={queryClient}>
        <App />
      </QueryClientProvider>
    </ReactiveProvider>
  </React.StrictMode>,
)
