// packages/react/src/hooks/useBuildTransaction.ts
'use client'

import type { Compute } from '@growae/reactive'
import {
  type BuildTransactionErrorType,
  type BuildTransactionParameters,
  type BuildTransactionReturnType,
  buildTransaction,
} from '@growae/reactive'
import { useMutation } from '@tanstack/react-query'
import type { ConfigParameter } from '../types/properties.js'
import type { UseMutationReturnType } from '../utils/query.js'
import { useConfig } from './useConfig.js'

export type UseBuildTransactionParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (
        data: BuildTransactionReturnType,
        variables: BuildTransactionParameters,
        context: context,
      ) => void
      onError?: (
        error: BuildTransactionErrorType,
        variables: BuildTransactionParameters,
        context: context,
      ) => void
    }
  }
>

export type UseBuildTransactionReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    BuildTransactionReturnType,
    BuildTransactionErrorType,
    BuildTransactionParameters,
    context
  > & {
    buildTransaction: (variables: BuildTransactionParameters) => void
    buildTransactionAsync: (
      variables: BuildTransactionParameters,
    ) => Promise<BuildTransactionReturnType>
  }
>

export function useBuildTransaction<context = unknown>(
  parameters: UseBuildTransactionParameters<context> = {},
): UseBuildTransactionReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['buildTransaction'],
    mutationFn: (variables: BuildTransactionParameters) =>
      buildTransaction(config, variables),
    ...parameters.mutation,
  } as any)

  type Return = UseBuildTransactionReturnType<context>
  return {
    ...(mutation as unknown as Return),
    buildTransaction: mutation.mutate as unknown as Return['buildTransaction'],
    buildTransactionAsync:
      mutation.mutateAsync as unknown as Return['buildTransactionAsync'],
  }
}

// packages/solid/src/primitives/useBuildTransaction.ts
import {
  type BuildTransactionParameters,
  buildTransaction,
  type Config,
} from '@growae/reactive'
import { createMutation } from '@tanstack/solid-query'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig'

export type UseBuildTransactionParameters = Accessor<{
  config?: Config | undefined
}>

export function useBuildTransaction(
  parameters: UseBuildTransactionParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['buildTransaction'],
    mutationFn: (variables: BuildTransactionParameters) =>
      buildTransaction(config(), variables),
  }))
}

export type UseBuildTransactionReturnType = ReturnType<
  typeof useBuildTransaction
>
