// packages/react/src/hooks/useConnections.ts
'use client'

import {
  type GetConnectionsReturnType,
  getConnections,
  watchConnections,
} from '@growae/reactive'
import { useSyncExternalStore } from 'react'
import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'

export type UseConnectionsParameters = ConfigParameter

export type UseConnectionsReturnType = GetConnectionsReturnType

export function useConnections(
  parameters: UseConnectionsParameters = {},
): UseConnectionsReturnType {
  const config = useConfig(parameters)

  return useSyncExternalStore(
    (onChange) => watchConnections(config, { onChange }),
    () => getConnections(config),
    () => getConnections(config),
  )
}

// packages/solid/src/primitives/useConnections.ts
import {
  type GetConnectionsReturnType,
  getConnections,
  watchConnections,
} from '@growae/reactive'
import { type Accessor, createEffect, createSignal, onCleanup } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseConnectionsParameters = Accessor<{
  config?: import('@growae/reactive').Config | undefined
}>

export type UseConnectionsReturnType = Accessor<GetConnectionsReturnType>

export function useConnections(
  parameters: UseConnectionsParameters = () => ({}),
): UseConnectionsReturnType {
  const config = useConfig(parameters)
  const [connections, setConnections] = createSignal(getConnections(config()))

  createEffect(() => {
    const _config = config()
    setConnections(() => getConnections(_config))
    const unsubscribe = watchConnections(_config, {
      onChange(data) {
        setConnections(() => data)
      },
    })
    onCleanup(() => unsubscribe())
  })

  return connections
}
