// packages/react/src/hooks/useConnection.ts
'use client'

import {
  type GetConnectionReturnType,
  getConnection,
  watchConnection,
} from '@growae/reactive'
import { useSyncExternalStore } from 'react'
import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'

export type UseConnectionParameters = ConfigParameter

export type UseConnectionReturnType = GetConnectionReturnType

export function useConnection(
  parameters: UseConnectionParameters = {},
): UseConnectionReturnType {
  const config = useConfig(parameters)

  return useSyncExternalStore(
    (onChange) => watchConnection(config, { onChange }),
    () => getConnection(config),
    () => getConnection(config),
  )
}

// packages/solid/src/primitives/useConnection.ts
import {
  type Config,
  type GetConnectionReturnType,
  getConnection,
  watchConnection,
} from '@growae/reactive'
import { type Accessor, createEffect, createSignal, onCleanup } from 'solid-js'
import { useConfig } from './useConfig'

export type UseConnectionParameters = Accessor<{
  config?: Config | undefined
}>

export type UseConnectionReturnType = Accessor<GetConnectionReturnType>

export function useConnection(
  parameters: UseConnectionParameters = () => ({}),
): UseConnectionReturnType {
  const config = useConfig(parameters)
  const [connection, setConnection] = createSignal(getConnection(config()))

  createEffect(() => {
    const _config = config()
    setConnection(() => getConnection(_config))
    const unsubscribe = watchConnection(_config, {
      onChange(data) {
        setConnection(() => data)
      },
    })
    onCleanup(() => unsubscribe())
  })

  return connection
}
