// packages/react/src/hooks/useConnectors.ts
'use client'

import {
  type GetConnectorsReturnType,
  getConnectors,
  watchConnectors,
} from '@reactive/core'
import { useSyncExternalStore } from 'react'
import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'

export type UseConnectorsParameters = ConfigParameter

export type UseConnectorsReturnType = GetConnectorsReturnType

export function useConnectors(
  parameters: UseConnectorsParameters = {},
): UseConnectorsReturnType {
  const config = useConfig(parameters)

  return useSyncExternalStore(
    (onChange) => watchConnectors(config, { onChange }),
    () => getConnectors(config),
    () => getConnectors(config),
  )
}

// packages/solid/src/primitives/useConnectors.ts
import {
  type GetConnectorsReturnType,
  getConnectors,
  watchConnectors,
} from '@reactive/core'
import { type Accessor, createEffect, createSignal, onCleanup } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseConnectorsParameters = Accessor<{ config?: import('@reactive/core').Config | undefined }>

export type UseConnectorsReturnType = Accessor<GetConnectorsReturnType>

export function useConnectors(
  parameters: UseConnectorsParameters = () => ({}),
): UseConnectorsReturnType {
  const config = useConfig(parameters)
  const [connectors, setConnectors] = createSignal(getConnectors(config()))

  createEffect(() => {
    const _config = config()
    setConnectors(() => getConnectors(_config))
    const unsubscribe = watchConnectors(_config, {
      onChange(data) {
        setConnectors(() => data)
      },
    })
    onCleanup(() => unsubscribe())
  })

  return connectors
}
