// packages/react/src/hooks/useEstimateGas.ts
'use client'

import {
  type EstimateGasErrorType,
  type EstimateGasParameters,
  type EstimateGasReturnType,
  estimateGas,
} from '@growae/reactive'
import type { Compute } from '@growae/reactive'
import type { ConfigParameter } from '../types/properties.js'
import { type UseQueryReturnType, useQuery } from '../utils/query.js'
import { useConfig } from './useConfig.js'
import { useNetworkId } from './useNetworkId.js'

export type UseEstimateGasParameters = Compute<
  EstimateGasParameters & ConfigParameter & { enabled?: boolean }
>

export type UseEstimateGasReturnType = UseQueryReturnType<
  EstimateGasReturnType,
  EstimateGasErrorType
>

export function useEstimateGas(
  parameters: UseEstimateGasParameters = {} as UseEstimateGasParameters,
): UseEstimateGasReturnType {
  const config = useConfig(parameters)
  const networkId = useNetworkId({ config })

  return useQuery({
    queryKey: [
      'estimateGas',
      {
        tx: parameters.tx,
        accountAddress: parameters.accountAddress,
        networkId: parameters.networkId ?? networkId,
      },
    ],
    queryFn: () =>
      estimateGas(config, {
        ...parameters,
        networkId: parameters.networkId ?? networkId,
      }),
    enabled:
      Boolean(parameters.tx && parameters.accountAddress) &&
      (parameters.enabled ?? true),
  }) as UseEstimateGasReturnType
}

// packages/solid/src/primitives/useEstimateGas.ts
import {
  type Config,
  type EstimateGasErrorType,
  type EstimateGasParameters,
  type EstimateGasReturnType,
  estimateGas,
} from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { createMemo } from 'solid-js'
import { type UseQueryReturnType, useQuery } from '../utils/query.js'
import { useConfig } from './useConfig.js'
import { useNetworkId } from './useNetworkId.js'

export type UseEstimateGasParameters = Accessor<
  EstimateGasParameters & {
    config?: Config | undefined
    enabled?: boolean
  }
>

export type UseEstimateGasReturnType = UseQueryReturnType<
  EstimateGasReturnType,
  EstimateGasErrorType
>

export function useEstimateGas(
  parameters: UseEstimateGasParameters = () => ({}) as EstimateGasParameters,
): UseEstimateGasReturnType {
  const config = useConfig(parameters)
  const networkId = useNetworkId(() => ({ config: config() }))

  const options = createMemo(() => ({
    queryKey: [
      'estimateGas',
      {
        tx: parameters().tx,
        accountAddress: parameters().accountAddress,
        networkId: parameters().networkId ?? networkId(),
      },
    ] as const,
    queryFn: () =>
      estimateGas(config(), {
        ...parameters(),
        networkId: parameters().networkId ?? networkId(),
      }),
    enabled:
      Boolean(parameters().tx && parameters().accountAddress) &&
      (parameters().enabled ?? true),
  }))

  return useQuery(options) as UseEstimateGasReturnType
}
