// packages/react/src/hooks/useNetworkId.ts
'use client'

import {
  type GetNetworkIdReturnType,
  getNetworkId,
  watchNetworkId,
} from '@growae/reactive'
import { useSyncExternalStore } from 'react'
import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'

export type UseNetworkIdParameters = ConfigParameter

export type UseNetworkIdReturnType = GetNetworkIdReturnType

export function useNetworkId(
  parameters: UseNetworkIdParameters = {},
): UseNetworkIdReturnType {
  const config = useConfig(parameters)

  return useSyncExternalStore(
    (onChange) => watchNetworkId(config, { onChange }),
    () => getNetworkId(config),
    () => getNetworkId(config),
  )
}

// packages/solid/src/primitives/useNetworkId.ts
import {
  type Config,
  type GetNetworkIdReturnType,
  getNetworkId,
  watchNetworkId,
} from '@growae/reactive'
import { type Accessor, createEffect, createSignal, onCleanup } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseNetworkIdParameters = Accessor<{
  config?: Config | undefined
}>

export type UseNetworkIdReturnType = Accessor<GetNetworkIdReturnType>

export function useNetworkId(
  parameters: UseNetworkIdParameters = () => ({}),
): UseNetworkIdReturnType {
  const config = useConfig(parameters)
  const [networkId, setNetworkId] = createSignal(getNetworkId(config()))

  createEffect(() => {
    const _config = config()
    setNetworkId(() => getNetworkId(_config))
    const unsubscribe = watchNetworkId(_config, {
      onChange(data) {
        setNetworkId(() => data)
      },
    })
    onCleanup(() => unsubscribe())
  })

  return networkId
}
