// packages/react/src/hooks/useNodeClient.ts
'use client'

import type { Compute } from '@growae/reactive'
import {
  type GetNodeClientParameters,
  type GetNodeClientReturnType,
  getNodeClient,
  watchNodeClient,
} from '@growae/reactive'
import { useSyncExternalStore } from 'react'
import type { ConfigParameter } from '../types/properties'
import { useConfig } from './useConfig'

export type UseNodeClientParameters = Compute<
  GetNodeClientParameters & ConfigParameter
>

export type UseNodeClientReturnType = GetNodeClientReturnType

export function useNodeClient(
  parameters: UseNodeClientParameters = {},
): UseNodeClientReturnType {
  const config = useConfig(parameters)

  return useSyncExternalStore(
    (onChange) => watchNodeClient(config, { onChange }),
    () => getNodeClient(config, parameters),
    () => getNodeClient(config, parameters),
  )
}

// packages/solid/src/primitives/useNodeClient.ts
import {
  type GetNodeClientParameters,
  type GetNodeClientReturnType,
  getNodeClient,
  watchNodeClient,
} from '@growae/reactive'
import { type Accessor, createEffect, createSignal, onCleanup } from 'solid-js'
import { useConfig } from './useConfig'

export type UseNodeClientParameters = Accessor<
  GetNodeClientParameters & {
    config?: import('@growae/reactive').Config | undefined
  }
>

export type UseNodeClientReturnType = Accessor<GetNodeClientReturnType>

export function useNodeClient(
  parameters: UseNodeClientParameters = () => ({}),
): UseNodeClientReturnType {
  const config = useConfig(parameters)
  const [nodeClient, setNodeClient] = createSignal(
    getNodeClient(config(), parameters()),
  )

  createEffect(() => {
    const _config = config()
    setNodeClient(() => getNodeClient(_config, parameters()))
    const unsubscribe = watchNodeClient(_config, {
      onChange(data) {
        setNodeClient(() => data)
      },
    })
    onCleanup(() => unsubscribe())
  })

  return nodeClient
}
