// packages/react/src/hooks/useNetworks.ts
'use client'

import {
  type GetNetworksReturnType,
  getNetworks,
} from '@growae/reactive'
import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'

export type UseNetworksParameters = ConfigParameter

export type UseNetworksReturnType = GetNetworksReturnType

export function useNetworks(
  parameters: UseNetworksParameters = {},
): UseNetworksReturnType {
  const config = useConfig(parameters)
  return getNetworks(config)
}

// packages/solid/src/primitives/useNetworks.ts
import {
  type Config,
  type GetNetworksReturnType,
  getNetworks,
} from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { createMemo } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseNetworksParameters = Accessor<{
  config?: Config | undefined
}>

export type UseNetworksReturnType = Accessor<GetNetworksReturnType>

export function useNetworks(
  parameters: UseNetworksParameters = () => ({}),
): UseNetworksReturnType {
  const config = useConfig(parameters)
  return createMemo(() => getNetworks(config()))
}
