// packages/react/src/hooks/useOpenChannel.ts
'use client'

import { useMutation } from '@tanstack/react-query'
import {
  type OpenChannelParameters,
  type OpenChannelReturnType,
  openChannel,
} from '@reactive/core'
import type { Compute } from '@reactive/core'
import type { ConfigParameter } from '../types/properties.js'
import type { UseMutationReturnType } from '../utils/query.js'
import { useConfig } from './useConfig.js'

export type UseOpenChannelParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (data: OpenChannelReturnType, variables: OpenChannelParameters, context: context) => void
      onError?: (error: Error, variables: OpenChannelParameters, context: context) => void
    }
  }
>

export type UseOpenChannelReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    OpenChannelReturnType,
    Error,
    OpenChannelParameters,
    context
  > & {
    openChannel: (variables: OpenChannelParameters) => void
    openChannelAsync: (variables: OpenChannelParameters) => Promise<OpenChannelReturnType>
  }
>

export function useOpenChannel<context = unknown>(
  parameters: UseOpenChannelParameters<context> = {},
): UseOpenChannelReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['openChannel'],
    mutationFn: (variables: OpenChannelParameters) =>
      openChannel(config, variables),
    ...parameters.mutation,
  })

  type Return = UseOpenChannelReturnType<context>
  return {
    ...(mutation as unknown as Return),
    openChannel: mutation.mutate as Return['openChannel'],
    openChannelAsync: mutation.mutateAsync as Return['openChannelAsync'],
  }
}

// packages/solid/src/primitives/useOpenChannel.ts
import { createMutation } from '@tanstack/solid-query'
import {
  type OpenChannelParameters,
  type OpenChannelReturnType,
  openChannel,
} from '@reactive/core'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseOpenChannelParameters = Accessor<{ config?: import('@reactive/core').Config | undefined }>

export function useOpenChannel(
  parameters: UseOpenChannelParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['openChannel'],
    mutationFn: (variables: OpenChannelParameters) =>
      openChannel(config(), variables),
  }))
}

export type UseOpenChannelReturnType = ReturnType<typeof useOpenChannel>
