// packages/react/src/hooks/useQueryOracle.ts
'use client'

import { useMutation } from '@tanstack/react-query'
import {
  type QueryOracleParameters,
  type QueryOracleReturnType,
  queryOracle,
} from '@growae/reactive'
import type { Compute } from '@growae/reactive'
import type { ConfigParameter } from '../types/properties.js'
import type { UseMutationReturnType } from '../utils/query.js'
import { useConfig } from './useConfig.js'

export type UseQueryOracleParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (data: QueryOracleReturnType, variables: QueryOracleParameters, context: context) => void
      onError?: (error: Error, variables: QueryOracleParameters, context: context) => void
    }
  }
>

export type UseQueryOracleReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    QueryOracleReturnType,
    Error,
    QueryOracleParameters,
    context
  > & {
    queryOracle: (variables: QueryOracleParameters) => void
    queryOracleAsync: (variables: QueryOracleParameters) => Promise<QueryOracleReturnType>
  }
>

export function useQueryOracle<context = unknown>(
  parameters: UseQueryOracleParameters<context> = {},
): UseQueryOracleReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['queryOracle'],
    mutationFn: (variables: QueryOracleParameters) =>
      queryOracle(config, variables),
    ...parameters.mutation,
  })

  type Return = UseQueryOracleReturnType<context>
  return {
    ...(mutation as unknown as Return),
    queryOracle: mutation.mutate as Return['queryOracle'],
    queryOracleAsync: mutation.mutateAsync as Return['queryOracleAsync'],
  }
}

// packages/solid/src/primitives/useQueryOracle.ts
import { createMutation } from '@tanstack/solid-query'
import {
  type QueryOracleParameters,
  type QueryOracleReturnType,
  queryOracle,
} from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseQueryOracleParameters = Accessor<{ config?: import('@growae/reactive').Config | undefined }>

export function useQueryOracle(
  parameters: UseQueryOracleParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['queryOracle'],
    mutationFn: (variables: QueryOracleParameters) =>
      queryOracle(config(), variables),
  }))
}

export type UseQueryOracleReturnType = ReturnType<typeof useQueryOracle>
