// packages/react/src/hooks/useRevokeName.ts
'use client'

import { useMutation } from '@tanstack/react-query'
import {
  type RevokeNameParameters,
  type RevokeNameReturnType,
  revokeName,
} from '@reactive/core'
import type { Compute } from '@reactive/core'
import type { ConfigParameter } from '../types/properties.js'
import type { UseMutationReturnType } from '../utils/query.js'
import { useConfig } from './useConfig.js'

export type UseRevokeNameParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (data: RevokeNameReturnType, variables: RevokeNameParameters, context: context) => void
      onError?: (error: Error, variables: RevokeNameParameters, context: context) => void
    }
  }
>

export type UseRevokeNameReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    RevokeNameReturnType,
    Error,
    RevokeNameParameters,
    context
  > & {
    revokeName: (variables: RevokeNameParameters) => void
    revokeNameAsync: (variables: RevokeNameParameters) => Promise<RevokeNameReturnType>
  }
>

export function useRevokeName<context = unknown>(
  parameters: UseRevokeNameParameters<context> = {},
): UseRevokeNameReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['revokeName'],
    mutationFn: (variables: RevokeNameParameters) =>
      revokeName(config, variables),
    ...parameters.mutation,
  })

  type Return = UseRevokeNameReturnType<context>
  return {
    ...(mutation as unknown as Return),
    revokeName: mutation.mutate as Return['revokeName'],
    revokeNameAsync: mutation.mutateAsync as Return['revokeNameAsync'],
  }
}

// packages/solid/src/primitives/useRevokeName.ts
import { createMutation } from '@tanstack/solid-query'
import {
  type RevokeNameParameters,
  type RevokeNameReturnType,
  revokeName,
} from '@reactive/core'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseRevokeNameParameters = Accessor<{ config?: import('@reactive/core').Config | undefined }>

export function useRevokeName(
  parameters: UseRevokeNameParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['revokeName'],
    mutationFn: (variables: RevokeNameParameters) =>
      revokeName(config(), variables),
  }))
}

export type UseRevokeNameReturnType = ReturnType<typeof useRevokeName>
