// packages/react/src/hooks/useRegisterOracle.ts
'use client'

import type { Compute } from '@growae/reactive'
import {
  type RegisterOracleParameters,
  type RegisterOracleReturnType,
  registerOracle,
} from '@growae/reactive'
import { useMutation } from '@tanstack/react-query'
import type { ConfigParameter } from '../types/properties'
import type { UseMutationReturnType } from '../utils/query'
import { useConfig } from './useConfig'

export type UseRegisterOracleParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (
        data: RegisterOracleReturnType,
        variables: RegisterOracleParameters,
        context: context,
      ) => void
      onError?: (
        error: Error,
        variables: RegisterOracleParameters,
        context: context,
      ) => void
    }
  }
>

export type UseRegisterOracleReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    RegisterOracleReturnType,
    Error,
    RegisterOracleParameters,
    context
  > & {
    registerOracle: (variables: RegisterOracleParameters) => void
    registerOracleAsync: (
      variables: RegisterOracleParameters,
    ) => Promise<RegisterOracleReturnType>
  }
>

export function useRegisterOracle<context = unknown>(
  parameters: UseRegisterOracleParameters<context> = {},
): UseRegisterOracleReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['registerOracle'],
    mutationFn: (variables: RegisterOracleParameters) =>
      registerOracle(config, variables),
    ...parameters.mutation,
  } as any)

  type Return = UseRegisterOracleReturnType<context>
  return {
    ...(mutation as unknown as Return),
    registerOracle: mutation.mutate as unknown as Return['registerOracle'],
    registerOracleAsync:
      mutation.mutateAsync as unknown as Return['registerOracleAsync'],
  }
}

// packages/solid/src/primitives/useRegisterOracle.ts
import { createMutation } from '@tanstack/solid-query'
import {
  type RegisterOracleParameters,
  type RegisterOracleReturnType,
  registerOracle,
} from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseRegisterOracleParameters = Accessor<{ config?: import('@growae/reactive').Config | undefined }>

export function useRegisterOracle(
  parameters: UseRegisterOracleParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['registerOracle'],
    mutationFn: (variables: RegisterOracleParameters) =>
      registerOracle(config(), variables),
  }))
}

export type UseRegisterOracleReturnType = ReturnType<typeof useRegisterOracle>
