// packages/react/src/hooks/useUpdateName.ts
'use client'

import {
  type UpdateNameParameters,
  type UpdateNameReturnType,
  updateName,
} from '@growae/reactive'
import type { Compute } from '@growae/reactive'
import { useMutation } from '@tanstack/react-query'
import type { ConfigParameter } from '../types/properties.js'
import type { UseMutationReturnType } from '../utils/query.js'
import { useConfig } from './useConfig.js'

export type UseUpdateNameParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (
        data: UpdateNameReturnType,
        variables: UpdateNameParameters,
        context: context,
      ) => void
      onError?: (
        error: Error,
        variables: UpdateNameParameters,
        context: context,
      ) => void
    }
  }
>

export type UseUpdateNameReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    UpdateNameReturnType,
    Error,
    UpdateNameParameters,
    context
  > & {
    updateName: (variables: UpdateNameParameters) => void
    updateNameAsync: (
      variables: UpdateNameParameters,
    ) => Promise<UpdateNameReturnType>
  }
>

export function useUpdateName<context = unknown>(
  parameters: UseUpdateNameParameters<context> = {},
): UseUpdateNameReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['updateName'],
    mutationFn: (variables: UpdateNameParameters) =>
      updateName(config, variables),
    ...parameters.mutation,
  })

  type Return = UseUpdateNameReturnType<context>
  return {
    ...(mutation as unknown as Return),
    updateName: mutation.mutate as Return['updateName'],
    updateNameAsync: mutation.mutateAsync as Return['updateNameAsync'],
  }
}

// packages/solid/src/primitives/useUpdateName.ts
import {
  type UpdateNameParameters,
  type UpdateNameReturnType,
  updateName,
} from '@growae/reactive'
import { createMutation } from '@tanstack/solid-query'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseUpdateNameParameters = Accessor<{
  config?: import('@growae/reactive').Config | undefined
}>

export function useUpdateName(
  parameters: UseUpdateNameParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['updateName'],
    mutationFn: (variables: UpdateNameParameters) =>
      updateName(config(), variables),
  }))
}

export type UseUpdateNameReturnType = ReturnType<typeof useUpdateName>
