// packages/react/src/hooks/useVerifyTypedData.ts
'use client'

import {
  type VerifyTypedDataErrorType,
  type VerifyTypedDataParameters,
  type VerifyTypedDataReturnType,
  verifyTypedData,
} from '@growae/reactive'
import type { Compute } from '@growae/reactive'
import type { ConfigParameter } from '../types/properties'
import { type UseQueryReturnType, useQuery } from '../utils/query'
import { useConfig } from './useConfig'

export type UseVerifyTypedDataParameters = Compute<
  VerifyTypedDataParameters & ConfigParameter & { enabled?: boolean }
>

export type UseVerifyTypedDataReturnType = UseQueryReturnType<
  VerifyTypedDataReturnType,
  VerifyTypedDataErrorType
>

export function useVerifyTypedData(
  parameters: UseVerifyTypedDataParameters = {} as UseVerifyTypedDataParameters,
): UseVerifyTypedDataReturnType {
  const config = useConfig(parameters)

  return useQuery({
    queryKey: [
      'verifyTypedData',
      {
        data: parameters.data,
        signature: parameters.signature,
        address: parameters.address,
      },
    ],
    queryFn: () => verifyTypedData(config, parameters),
    enabled:
      Boolean(parameters.data && parameters.signature && parameters.address) &&
      (parameters.enabled ?? true),
  }) as UseVerifyTypedDataReturnType
}

// packages/solid/src/primitives/useVerifyTypedData.ts
import {
  type VerifyTypedDataParameters,
  type VerifyTypedDataReturnType,
  type VerifyTypedDataErrorType,
  verifyTypedData,
} from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { createMemo } from 'solid-js'
import { type UseQueryReturnType, useQuery } from '../utils/query.js'
import { useConfig } from './useConfig.js'

export type UseVerifyTypedDataParameters = Accessor<
  VerifyTypedDataParameters & {
    config?: import('@growae/reactive').Config | undefined
    enabled?: boolean
  }
>

export type UseVerifyTypedDataReturnType = UseQueryReturnType<
  VerifyTypedDataReturnType,
  VerifyTypedDataErrorType
>

export function useVerifyTypedData(
  parameters: UseVerifyTypedDataParameters = () => ({} as VerifyTypedDataParameters),
): UseVerifyTypedDataReturnType {
  const config = useConfig(parameters)

  const options = createMemo(() => ({
    queryKey: ['verifyTypedData', {
      data: parameters().data,
      signature: parameters().signature,
      address: parameters().address,
    }] as const,
    queryFn: () => verifyTypedData(config(), parameters()),
    enabled: Boolean(
      parameters().data && parameters().signature && parameters().address,
    ) && (parameters().enabled ?? true),
  }))

  return useQuery(options) as UseVerifyTypedDataReturnType
}
