// packages/react/src/hooks/useWatchConnection.ts
'use client'

import { watchConnection } from '@growae/reactive'
import type { Compute, Connection } from '@growae/reactive'
import { useEffect, useRef } from 'react'
import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'

export type UseWatchConnectionParameters = Compute<
  ConfigParameter & {
    onChange: (connection: Connection | undefined) => void
    enabled?: boolean
  }
>

export type UseWatchConnectionReturnType = void

export function useWatchConnection(
  parameters: UseWatchConnectionParameters,
): UseWatchConnectionReturnType {
  const { enabled = true } = parameters
  const config = useConfig(parameters)

  const onChangeRef = useRef(parameters.onChange)
  onChangeRef.current = parameters.onChange

  useEffect(() => {
    if (!enabled) return
    if (!onChangeRef.current) return
    return watchConnection(config, {
      onChange: (connection) => onChangeRef.current?.(connection),
    })
  }, [config, enabled])
}

// packages/solid/src/primitives/useWatchConnection.ts
import { watchConnection } from '@growae/reactive'
import type { Connection } from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { createEffect, onCleanup } from 'solid-js'
import { useConfig } from './useConfig'

export type UseWatchConnectionParameters = Accessor<{
  config?: import('@growae/reactive').Config | undefined
  onChange: (connection: Connection | undefined) => void
  enabled?: boolean
}>

export type UseWatchConnectionReturnType = void

export function useWatchConnection(
  parameters: UseWatchConnectionParameters,
): UseWatchConnectionReturnType {
  const config = useConfig(parameters)

  createEffect(() => {
    const { enabled = true, onChange } = parameters()
    if (!enabled) return
    if (!onChange) return

    const unwatch = watchConnection(config(), {
      onChange,
    })
    onCleanup(() => unwatch())
  })
}
