// packages/solid/src/primitives/useActiveAccount.ts
import {
  type Config,
  type GetActiveAccountReturnType,
  getActiveAccount,
  watchActiveAccount,
} from '@growae/reactive'
import { type Accessor, createEffect, createSignal, onCleanup } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseActiveAccountParameters = Accessor<{
  config?: Config | undefined
}>

export type UseActiveAccountReturnType = Accessor<GetActiveAccountReturnType>

export function useActiveAccount(
  parameters: UseActiveAccountParameters = () => ({}),
): UseActiveAccountReturnType {
  const config = useConfig(parameters)
  const [activeAccount, setActiveAccount] = createSignal(
    getActiveAccount(config()),
  )

  createEffect(() => {
    const _config = config()
    setActiveAccount(() => getActiveAccount(_config))
    const unsubscribe = watchActiveAccount(_config, {
      onChange(data) {
        setActiveAccount(() => data)
      },
    })
    onCleanup(() => unsubscribe())
  })

  return activeAccount
}

// packages/react/src/hooks/useActiveAccount.ts
'use client'

import {
  type GetActiveAccountReturnType,
  getActiveAccount,
  watchActiveAccount,
} from '@growae/reactive'
import { useSyncExternalStore } from 'react'
import type { ConfigParameter } from '../types/properties'
import { useConfig } from './useConfig'

export type UseActiveAccountParameters = ConfigParameter

export type UseActiveAccountReturnType = GetActiveAccountReturnType

export function useActiveAccount(
  parameters: UseActiveAccountParameters = {},
): UseActiveAccountReturnType {
  const config = useConfig(parameters)

  return useSyncExternalStore(
    (onChange) =>
      watchActiveAccount(config, {
        onChange: () => onChange(),
      }),
    () => getActiveAccount(config),
    () => getActiveAccount(config),
  )
}
