// packages/solid/src/primitives/useConnect.ts
import { createMutation } from '@tanstack/solid-query'
import {
  type ConnectParameters,
  type ConnectReturnType,
  type ConnectErrorType,
  connect,
} from '@growae/reactive'
import { type Accessor, createEffect, onCleanup } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseConnectParameters = Accessor<{ config?: import('@growae/reactive').Config | undefined }>

export function useConnect(
  parameters: UseConnectParameters = () => ({}),
) {
  const config = useConfig(parameters)
  const mutation = createMutation(() => ({
    mutationKey: ['connect'],
    mutationFn: (variables: ConnectParameters) => connect(config(), variables),
  }))

  createEffect(() => {
    const unsubscribe = config().subscribe(
      ({ status }) => status,
      (status, previousStatus) => {
        if (previousStatus === 'connected' && status === 'disconnected') {
          mutation.reset()
        }
      },
    )
    onCleanup(() => unsubscribe())
  })

  return mutation
}

export type UseConnectReturnType = ReturnType<typeof useConnect>

// packages/react/src/hooks/useConnect.ts
'use client'

import {
  type Config,
  type ConnectErrorType,
  type ConnectParameters,
  type ConnectReturnType,
  connect,
} from '@growae/reactive'
import type { Compute } from '@growae/reactive'
import { useMutation } from '@tanstack/react-query'
import { useEffect } from 'react'
import type { ConfigParameter } from '../types/properties.js'
import type { UseMutationReturnType } from '../utils/query.js'
import { useConfig } from './useConfig.js'
import { useConnectors } from './useConnectors.js'

export type UseConnectParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (
        data: ConnectReturnType,
        variables: ConnectParameters,
        context: context,
      ) => void
      onError?: (
        error: ConnectErrorType,
        variables: ConnectParameters,
        context: context,
      ) => void
      onSettled?: (
        data: ConnectReturnType | undefined,
        error: ConnectErrorType | null,
        variables: ConnectParameters,
        context: context,
      ) => void
    }
  }
>

export type UseConnectReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    ConnectReturnType,
    ConnectErrorType,
    ConnectParameters,
    context
  > & {
    connect: (variables: ConnectParameters) => void
    connectAsync: (variables: ConnectParameters) => Promise<ConnectReturnType>
    connectors: ReturnType<typeof useConnectors>
  }
>

export function useConnect<context = unknown>(
  parameters: UseConnectParameters<context> = {},
): UseConnectReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['connect'],
    mutationFn: (variables: ConnectParameters) => connect(config, variables),
    ...parameters.mutation,
  })

  useEffect(() => {
    return config.subscribe(
      ({ status }) => status,
      (status, previousStatus) => {
        if (previousStatus === 'connected' && status === 'disconnected')
          mutation.reset()
      },
    )
  }, [config, mutation.reset])

  type Return = UseConnectReturnType<context>
  return {
    ...(mutation as unknown as Return),
    connect: mutation.mutate as Return['connect'],
    connectAsync: mutation.mutateAsync as Return['connectAsync'],
    connectors: useConnectors({ config }),
  }
}
