// packages/solid/src/primitives/useClaimName.ts
import {
  type ClaimNameParameters,
  type ClaimNameReturnType,
  claimName,
} from '@growae/reactive'
import { createMutation } from '@tanstack/solid-query'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseClaimNameParameters = Accessor<{
  config?: import('@growae/reactive').Config | undefined
}>

export function useClaimName(parameters: UseClaimNameParameters = () => ({})) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['claimName'],
    mutationFn: (variables: ClaimNameParameters) =>
      claimName(config(), variables),
  }))
}

export type UseClaimNameReturnType = ReturnType<typeof useClaimName>

// packages/react/src/hooks/useClaimName.ts
'use client'

import type { Compute } from '@growae/reactive'
import {
  type ClaimNameParameters,
  type ClaimNameReturnType,
  claimName,
} from '@growae/reactive'
import { useMutation } from '@tanstack/react-query'
import type { ConfigParameter } from '../types/properties.js'
import type { UseMutationReturnType } from '../utils/query.js'
import { useConfig } from './useConfig.js'

export type UseClaimNameParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (
        data: ClaimNameReturnType,
        variables: ClaimNameParameters,
        context: context,
      ) => void
      onError?: (
        error: Error,
        variables: ClaimNameParameters,
        context: context,
      ) => void
    }
  }
>

export type UseClaimNameReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    ClaimNameReturnType,
    Error,
    ClaimNameParameters,
    context
  > & {
    claimName: (variables: ClaimNameParameters) => void
    claimNameAsync: (
      variables: ClaimNameParameters,
    ) => Promise<ClaimNameReturnType>
  }
>

export function useClaimName<context = unknown>(
  parameters: UseClaimNameParameters<context> = {},
): UseClaimNameReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['claimName'],
    mutationFn: (variables: ClaimNameParameters) =>
      claimName(config, variables),
    ...parameters.mutation,
  } as any)

  type Return = UseClaimNameReturnType<context>
  return {
    ...(mutation as unknown as Return),
    claimName: mutation.mutate as unknown as Return['claimName'],
    claimNameAsync: mutation.mutateAsync as unknown as Return['claimNameAsync'],
  }
}
