// packages/solid/src/primitives/useConfig.ts
import type { Config } from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { createMemo, useContext } from 'solid-js'
import { ReactiveContext } from '../context'
import { ReactiveProviderNotFoundError } from '../errors/context'

export type UseConfigParameters = Accessor<{ config?: Config | undefined }>

export type UseConfigReturnType = Accessor<Config>

export function useConfig(
  parameters: UseConfigParameters = () => ({}),
): UseConfigReturnType {
  return createMemo(() => {
    const config = parameters().config ?? useContext(ReactiveContext)
    if (!config) throw new ReactiveProviderNotFoundError()
    return config
  })
}

// packages/react/src/hooks/useConfig.ts
'use client'

import type { Config } from '@growae/reactive'
import { useContext } from 'react'
import { ReactiveContext } from '../context.js'
import { ReactiveProviderNotFoundError } from '../errors/context.js'
import type { ConfigParameter } from '../types/properties.js'

export type UseConfigParameters<config extends Config = Config> =
  ConfigParameter<config>

export type UseConfigReturnType<config extends Config = Config> = config

export function useConfig<config extends Config = Config>(
  parameters: UseConfigParameters<config> = {},
): UseConfigReturnType<config> {
  const config = parameters.config ?? useContext(ReactiveContext)
  if (!config) throw new ReactiveProviderNotFoundError()
  return config as UseConfigReturnType<config>
}
