// packages/solid/src/primitives/useChannelDeposit.ts
import { createMutation } from '@tanstack/solid-query'
import {
  type ChannelDepositParameters,
  type ChannelDepositReturnType,
  channelDeposit,
} from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseChannelDepositParameters = Accessor<{ config?: import('@growae/reactive').Config | undefined }>

export function useChannelDeposit(
  parameters: UseChannelDepositParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['channelDeposit'],
    mutationFn: (variables: ChannelDepositParameters) =>
      channelDeposit(config(), variables),
  }))
}

export type UseChannelDepositReturnType = ReturnType<typeof useChannelDeposit>

// packages/react/src/hooks/useChannelDeposit.ts
'use client'

import {
  type ChannelDepositParameters,
  type ChannelDepositReturnType,
  channelDeposit,
} from '@growae/reactive'
import type { Compute } from '@growae/reactive'
import { useMutation } from '@tanstack/react-query'
import type { ConfigParameter } from '../types/properties.js'
import type { UseMutationReturnType } from '../utils/query.js'
import { useConfig } from './useConfig.js'

export type UseChannelDepositParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (
        data: ChannelDepositReturnType,
        variables: ChannelDepositParameters,
        context: context,
      ) => void
      onError?: (
        error: Error,
        variables: ChannelDepositParameters,
        context: context,
      ) => void
    }
  }
>

export type UseChannelDepositReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    ChannelDepositReturnType,
    Error,
    ChannelDepositParameters,
    context
  > & {
    channelDeposit: (variables: ChannelDepositParameters) => void
    channelDepositAsync: (
      variables: ChannelDepositParameters,
    ) => Promise<ChannelDepositReturnType>
  }
>

export function useChannelDeposit<context = unknown>(
  parameters: UseChannelDepositParameters<context> = {},
): UseChannelDepositReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['channelDeposit'],
    mutationFn: (variables: ChannelDepositParameters) =>
      channelDeposit(config, variables),
    ...parameters.mutation,
  } as any)

  type Return = UseChannelDepositReturnType<context>
  return {
    ...(mutation as unknown as Return),
    channelDeposit: mutation.mutate as unknown as Return['channelDeposit'],
    channelDepositAsync: mutation.mutateAsync as unknown as Return['channelDepositAsync'],
  }
}
