// packages/solid/src/primitives/useDeployContract.ts
import { createMutation } from '@tanstack/solid-query'
import {
  type DeployContractParameters,
  type DeployContractReturnType,
  type DeployContractErrorType,
  deployContract,
} from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseDeployContractParameters = Accessor<{ config?: import('@growae/reactive').Config | undefined }>

export function useDeployContract(
  parameters: UseDeployContractParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['deployContract'],
    mutationFn: (variables: DeployContractParameters) =>
      deployContract(config(), variables),
  }))
}

export type UseDeployContractReturnType = ReturnType<typeof useDeployContract>

// packages/react/src/hooks/useDeployContract.ts
'use client'

import {
  type DeployContractErrorType,
  type DeployContractParameters,
  type DeployContractReturnType,
  deployContract,
} from '@growae/reactive'
import type { Compute } from '@growae/reactive'
import { useMutation } from '@tanstack/react-query'
import type { ConfigParameter } from '../types/properties.js'
import type { UseMutationReturnType } from '../utils/query.js'
import { useConfig } from './useConfig.js'

export type UseDeployContractParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (
        data: DeployContractReturnType,
        variables: DeployContractParameters,
        context: context,
      ) => void
      onError?: (
        error: DeployContractErrorType,
        variables: DeployContractParameters,
        context: context,
      ) => void
    }
  }
>

export type UseDeployContractReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    DeployContractReturnType,
    DeployContractErrorType,
    DeployContractParameters,
    context
  > & {
    deployContract: (variables: DeployContractParameters) => void
    deployContractAsync: (
      variables: DeployContractParameters,
    ) => Promise<DeployContractReturnType>
  }
>

export function useDeployContract<context = unknown>(
  parameters: UseDeployContractParameters<context> = {},
): UseDeployContractReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['deployContract'],
    mutationFn: (variables: DeployContractParameters) =>
      deployContract(config, variables),
    ...parameters.mutation,
  } as any)

  type Return = UseDeployContractReturnType<context>
  return {
    ...(mutation as unknown as Return),
    deployContract: mutation.mutate as unknown as Return['deployContract'],
    deployContractAsync: mutation.mutateAsync as unknown as Return['deployContractAsync'],
  }
}
