// packages/solid/src/primitives/usePreclaimName.ts
import { createMutation } from '@tanstack/solid-query'
import {
  type PreclaimNameParameters,
  type PreclaimNameReturnType,
  preclaimName,
} from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UsePreclaimNameParameters = Accessor<{ config?: import('@growae/reactive').Config | undefined }>

export function usePreclaimName(
  parameters: UsePreclaimNameParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['preclaimName'],
    mutationFn: (variables: PreclaimNameParameters) =>
      preclaimName(config(), variables),
  }))
}

export type UsePreclaimNameReturnType = ReturnType<typeof usePreclaimName>

// packages/react/src/hooks/usePreclaimName.ts
'use client'

import {
  type PreclaimNameParameters,
  type PreclaimNameReturnType,
  preclaimName,
} from '@growae/reactive'
import type { Compute } from '@growae/reactive'
import { useMutation } from '@tanstack/react-query'
import type { ConfigParameter } from '../types/properties'
import type { UseMutationReturnType } from '../utils/query'
import { useConfig } from './useConfig'

export type UsePreclaimNameParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (
        data: PreclaimNameReturnType,
        variables: PreclaimNameParameters,
        context: context,
      ) => void
      onError?: (
        error: Error,
        variables: PreclaimNameParameters,
        context: context,
      ) => void
    }
  }
>

export type UsePreclaimNameReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    PreclaimNameReturnType,
    Error,
    PreclaimNameParameters,
    context
  > & {
    preclaimName: (variables: PreclaimNameParameters) => void
    preclaimNameAsync: (
      variables: PreclaimNameParameters,
    ) => Promise<PreclaimNameReturnType>
  }
>

export function usePreclaimName<context = unknown>(
  parameters: UsePreclaimNameParameters<context> = {},
): UsePreclaimNameReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['preclaimName'],
    mutationFn: (variables: PreclaimNameParameters) =>
      preclaimName(config, variables),
    ...parameters.mutation,
  } as any)

  type Return = UsePreclaimNameReturnType<context>
  return {
    ...(mutation as unknown as Return),
    preclaimName: mutation.mutate as unknown as Return['preclaimName'],
    preclaimNameAsync:
      mutation.mutateAsync as unknown as Return['preclaimNameAsync'],
  }
}
