// packages/solid/src/primitives/useSignMessage.ts
import {
  type SignMessageErrorType,
  type SignMessageParameters,
  type SignMessageReturnType,
  signMessage,
} from '@growae/reactive'
import { createMutation } from '@tanstack/solid-query'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseSignMessageParameters = Accessor<{
  config?: import('@growae/reactive').Config | undefined
}>

export function useSignMessage(
  parameters: UseSignMessageParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['signMessage'],
    mutationFn: (variables: SignMessageParameters) =>
      signMessage(config(), variables),
  }))
}

export type UseSignMessageReturnType = ReturnType<typeof useSignMessage>

// packages/react/src/hooks/useSignMessage.ts
'use client'

import type { Compute } from '@growae/reactive'
import {
  type SignMessageErrorType,
  type SignMessageParameters,
  type SignMessageReturnType,
  signMessage,
} from '@growae/reactive'
import { useMutation } from '@tanstack/react-query'
import type { ConfigParameter } from '../types/properties.js'
import type { UseMutationReturnType } from '../utils/query.js'
import { useConfig } from './useConfig.js'

export type UseSignMessageParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (
        data: SignMessageReturnType,
        variables: SignMessageParameters,
        context: context,
      ) => void
      onError?: (
        error: SignMessageErrorType,
        variables: SignMessageParameters,
        context: context,
      ) => void
    }
  }
>

export type UseSignMessageReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    SignMessageReturnType,
    SignMessageErrorType,
    SignMessageParameters,
    context
  > & {
    signMessage: (variables: SignMessageParameters) => void
    signMessageAsync: (
      variables: SignMessageParameters,
    ) => Promise<SignMessageReturnType>
  }
>

export function useSignMessage<context = unknown>(
  parameters: UseSignMessageParameters<context> = {},
): UseSignMessageReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['signMessage'],
    mutationFn: (variables: SignMessageParameters) =>
      signMessage(config, variables),
    ...parameters.mutation,
  } as any)

  type Return = UseSignMessageReturnType<context>
  return {
    ...(mutation as unknown as Return),
    signMessage: mutation.mutate as unknown as Return['signMessage'],
    signMessageAsync:
      mutation.mutateAsync as unknown as Return['signMessageAsync'],
  }
}
