// packages/solid/src/primitives/useSwitchActiveAccount.ts
import {
  type Config,
  type SwitchActiveAccountParameters,
  switchActiveAccount,
} from '@growae/reactive'
import { createMutation } from '@tanstack/solid-query'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseSwitchActiveAccountParameters = Accessor<{
  config?: Config | undefined
}>

export function useSwitchActiveAccount(
  parameters: UseSwitchActiveAccountParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['switchActiveAccount'],
    mutationFn: async (variables: SwitchActiveAccountParameters) => {
      switchActiveAccount(config(), variables)
    },
  }))
}

export type UseSwitchActiveAccountReturnType = ReturnType<
  typeof useSwitchActiveAccount
>

// packages/react/src/hooks/useSwitchActiveAccount.ts
'use client'

import {
  type SwitchActiveAccountParameters,
  switchActiveAccount,
} from '@growae/reactive'
import { useMutation } from '@tanstack/react-query'
import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'

export type UseSwitchActiveAccountParameters = ConfigParameter

export type UseSwitchActiveAccountReturnType = {
  switchActiveAccount: (params: SwitchActiveAccountParameters) => void
  isPending: boolean
  error: Error | null
}

export function useSwitchActiveAccount(
  parameters: UseSwitchActiveAccountParameters = {},
): UseSwitchActiveAccountReturnType {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['switchActiveAccount'],
    mutationFn: (params: SwitchActiveAccountParameters) => {
      switchActiveAccount(config, params)
      return Promise.resolve()
    },
  } as any)

  return {
    switchActiveAccount:
      mutation.mutate as unknown as UseSwitchActiveAccountReturnType['switchActiveAccount'],
    isPending: mutation.isPending,
    error: mutation.error,
  }
}
