// packages/solid/src/primitives/useSendTransaction.ts
import { createMutation } from '@tanstack/solid-query'
import {
  type SendTransactionParameters,
  type SendTransactionReturnType,
  type SendTransactionErrorType,
  sendTransaction,
} from '@reactive/core'
import type { Accessor } from 'solid-js'
import { useConfig } from './useConfig.js'

export type UseSendTransactionParameters = Accessor<{ config?: import('@reactive/core').Config | undefined }>

export function useSendTransaction(
  parameters: UseSendTransactionParameters = () => ({}),
) {
  const config = useConfig(parameters)
  return createMutation(() => ({
    mutationKey: ['sendTransaction'],
    mutationFn: (variables: SendTransactionParameters) =>
      sendTransaction(config(), variables),
  }))
}

export type UseSendTransactionReturnType = ReturnType<typeof useSendTransaction>

// packages/react/src/hooks/useSendTransaction.ts
'use client'

import { useMutation } from '@tanstack/react-query'
import {
  type SendTransactionParameters,
  type SendTransactionReturnType,
  type SendTransactionErrorType,
  sendTransaction,
} from '@reactive/core'
import type { Compute } from '@reactive/core'
import type { ConfigParameter } from '../types/properties.js'
import type { UseMutationReturnType } from '../utils/query.js'
import { useConfig } from './useConfig.js'

export type UseSendTransactionParameters<context = unknown> = Compute<
  ConfigParameter & {
    mutation?: {
      onSuccess?: (data: SendTransactionReturnType, variables: SendTransactionParameters, context: context) => void
      onError?: (error: SendTransactionErrorType, variables: SendTransactionParameters, context: context) => void
    }
  }
>

export type UseSendTransactionReturnType<context = unknown> = Compute<
  UseMutationReturnType<
    SendTransactionReturnType,
    SendTransactionErrorType,
    SendTransactionParameters,
    context
  > & {
    sendTransaction: (variables: SendTransactionParameters) => void
    sendTransactionAsync: (variables: SendTransactionParameters) => Promise<SendTransactionReturnType>
  }
>

export function useSendTransaction<context = unknown>(
  parameters: UseSendTransactionParameters<context> = {},
): UseSendTransactionReturnType<context> {
  const config = useConfig(parameters)

  const mutation = useMutation({
    mutationKey: ['sendTransaction'],
    mutationFn: (variables: SendTransactionParameters) =>
      sendTransaction(config, variables),
    ...parameters.mutation,
  })

  type Return = UseSendTransactionReturnType<context>
  return {
    ...(mutation as unknown as Return),
    sendTransaction: mutation.mutate as Return['sendTransaction'],
    sendTransactionAsync: mutation.mutateAsync as Return['sendTransactionAsync'],
  }
}
