// packages/solid/src/primitives/useWatchConnectors.ts
import { watchConnectors } from '@growae/reactive'
import type { Connector } from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { createEffect, onCleanup } from 'solid-js'
import { useConfig } from './useConfig'

export type UseWatchConnectorsParameters = Accessor<{
  config?: import('@growae/reactive').Config | undefined
  onChange: (connectors: readonly Connector[]) => void
  enabled?: boolean
}>

export type UseWatchConnectorsReturnType = void

export function useWatchConnectors(
  parameters: UseWatchConnectorsParameters,
): UseWatchConnectorsReturnType {
  const config = useConfig(parameters)

  createEffect(() => {
    const { enabled = true, onChange } = parameters()
    if (!enabled) return
    if (!onChange) return

    const unwatch = watchConnectors(config(), {
      onChange,
    })
    onCleanup(() => unwatch())
  })
}

// packages/react/src/hooks/useWatchConnectors.ts
'use client'

import type { Compute, Connector } from '@growae/reactive'
import { watchConnectors } from '@growae/reactive'
import { useEffect, useRef } from 'react'
import type { ConfigParameter } from '../types/properties'
import { useConfig } from './useConfig'

export type UseWatchConnectorsParameters = Compute<
  ConfigParameter & {
    onChange: (connectors: readonly Connector[]) => void
    enabled?: boolean
  }
>

export type UseWatchConnectorsReturnType = void

export function useWatchConnectors(
  parameters: UseWatchConnectorsParameters,
): UseWatchConnectorsReturnType {
  const { enabled = true } = parameters
  const config = useConfig(parameters)

  const onChangeRef = useRef(parameters.onChange)
  onChangeRef.current = parameters.onChange

  useEffect(() => {
    if (!enabled) return
    if (!onChangeRef.current) return
    return watchConnectors(config, {
      onChange: (connectors) => onChangeRef.current?.(connectors),
    })
  }, [config, enabled])
}
