// packages/solid/src/primitives/useWatchHeight.ts
import { type Config, watchHeight } from '@growae/reactive'
import type { Accessor } from 'solid-js'
import { createEffect, onCleanup } from 'solid-js'
import { useConfig } from './useConfig.js'
import { useNetworkId } from './useNetworkId.js'

export type UseWatchHeightParameters = Accessor<{
  config?: Config | undefined
  onHeight: (height: number) => void
  enabled?: boolean
  interval?: number
  networkId?: string
}>

export type UseWatchHeightReturnType = void

export function useWatchHeight(
  parameters: UseWatchHeightParameters,
): UseWatchHeightReturnType {
  const config = useConfig(parameters)
  const configNetworkId = useNetworkId(() => ({ config: config() }))

  createEffect(() => {
    const {
      enabled = true,
      interval,
      networkId: paramNetworkId,
      onHeight,
    } = parameters()
    if (!enabled) return
    if (!onHeight) return

    const networkId = paramNetworkId ?? configNetworkId()
    const unwatch = watchHeight(config(), {
      onChange: onHeight,
      pollingInterval: interval,
      networkId,
    })
    onCleanup(() => unwatch())
  })
}

// packages/react/src/hooks/useWatchHeight.ts
'use client'

import { watchHeight } from '@growae/reactive'
import type { Compute } from '@growae/reactive'
import { useEffect, useRef } from 'react'
import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'
import { useNetworkId } from './useNetworkId.js'

export type UseWatchHeightParameters = Compute<
  ConfigParameter & {
    onHeight: (height: number) => void
    enabled?: boolean
    interval?: number
    networkId?: string
  }
>

export type UseWatchHeightReturnType = void

export function useWatchHeight(
  parameters: UseWatchHeightParameters,
): UseWatchHeightReturnType {
  const { enabled = true, interval, networkId: paramNetworkId } = parameters
  const config = useConfig(parameters)
  const configNetworkId = useNetworkId({ config })
  const networkId = paramNetworkId ?? configNetworkId

  const onHeightRef = useRef(parameters.onHeight)
  onHeightRef.current = parameters.onHeight

  useEffect(() => {
    if (!enabled) return
    if (!onHeightRef.current) return
    return watchHeight(config, {
      onChange: (height) => onHeightRef.current?.(height),
      pollingInterval: interval,
      networkId,
    })
  }, [config, enabled, interval, networkId])
}
